### ISSUE TITLE
Project Walkthrough

### ISSUE THREAD

**Issue by BeardyMan37** [Bitsy-Chuck/Covid_Cough_Test#1]
Hello Bitsy-Chuck. Could you please provide a small documentation on how to run your project to achieve the accuracy? I am writing a report on cough sound classification, and it would help me a lot if I could verify your results.

**Comment by Bitsy-Chuck** [comment]
Yea.. I'm really sorry. will post the documentation and walkthrough asap. Been busy with work actually.
